### ISSUE TITLE
Quality Assurance: Stream settings hidden menu overflow

### ISSUE THREAD

**Issue by joyhchen** [zulip/zulip-gci#36]
1. Minimize window to mobile width (365px)
2. Press the hamburger menu icon to open list of streams
3. Press the down chevron to the right of any stream's name

The stream settings that extend after pressing the down chevron should overflow and be hidden outside of the window's view as seen in the picture.

![screenshot from 2016-11-27 18-13-44](https://cloud.githubusercontent.com/assets/7107181/20684655/91a3f796-b576-11e6-873f-a8108930e4ad.png)

**Comment by timabbott** [comment]
This bug report looks great!  Can you open a copy of this issue against the `zulip/zulip` repository?  You can grab the content of your report using the little pencil icon in the upper left.

Thanks @joyhchen!  

(BTW, I'm not sure it totally makes sense for the workflow for this task type to have folks open issues here and move them; I guess the advantage is you don't need to know which repo the relevant code is in and we can provide comments on the bug report writeup, but we might want to just have you open them on the correct project directly since that seems simpler...)
